//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by RpcNetGen 1.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpcNet.Internal
{
    using System;
    using System.Net;
    using RpcNet;

    internal static class RpcConstants
    {
    }

    internal partial class AcceptedReply : IXdrReadable, IXdrWritable
    {
        public OpaqueAuthentication Verifier { get; set; }
        public ReplyData ReplyData { get; set; }

        public AcceptedReply()
        {
        }

        public AcceptedReply(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            Verifier?.WriteTo(writer);
            ReplyData?.WriteTo(writer);
        }

        public void ReadFrom(IXdrReader reader)
        {
            Verifier = new OpaqueAuthentication(reader);
            ReplyData = new ReplyData(reader);
        }
    }

    internal enum AcceptStatus
    {
        Success = 0,
        ProgramUnavailable = 1,
        ProgramMismatch = 2,
        ProcedureUnavailable = 3,
        GarbageArguments = 4,
        SystemError = 5,
    }

    internal enum AuthenticationFlavor
    {
        None = 0,
        Unix = 1,
        Short = 2,
        Des = 3,
        Gss = 6,
    }

    internal enum AuthenticationStatus
    {
        Ok = 0,
        BadCredential = 1,
        RejectedCredential = 2,
        BadVerifier = 3,
        RejectedVerifier = 4,
        TooWeak = 5,
        InvalidResponseVerifier = 6,
        FailedUnknownReason = 7,
        KerberosGenericError = 8,
        TimeOfCredentialExpired = 9,
        ProblemWithTicketFile = 10,
        FailedToDecodeAuthenticator = 11,
        InvalidNetAddress = 12,
        GssMissingCredential = 13,
        GssContextProblem = 14,
    }

    internal partial class Body : IXdrReadable, IXdrWritable
    {
        public MessageType MessageType { get; set; }
        public CallBody CallBody { get; set; }
        public ReplyBody ReplyBody { get; set; }

        public Body()
        {
        }

        public Body(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write((int)MessageType);
            switch (MessageType)
            {
                case MessageType.Call:
                    CallBody?.WriteTo(writer);
                    break;
                case MessageType.Reply:
                    ReplyBody?.WriteTo(writer);
                    break;
            }
        }

        public void ReadFrom(IXdrReader reader)
        {
            MessageType = (MessageType)reader.ReadInt();
            switch (MessageType)
            {
                case MessageType.Call:
                    CallBody = new CallBody(reader);
                    break;
                case MessageType.Reply:
                    ReplyBody = new ReplyBody(reader);
                    break;
            }
        }
    }

    internal partial class CallBody : IXdrReadable, IXdrWritable
    {
        public uint RpcVersion { get; set; }
        public uint Program { get; set; }
        public uint Version { get; set; }
        public uint Procedure { get; set; }
        public OpaqueAuthentication Credential { get; set; }
        public OpaqueAuthentication Verifier { get; set; }

        public CallBody()
        {
        }

        public CallBody(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write(RpcVersion);
            writer.Write(Program);
            writer.Write(Version);
            writer.Write(Procedure);
            Credential?.WriteTo(writer);
            Verifier?.WriteTo(writer);
        }

        public void ReadFrom(IXdrReader reader)
        {
            RpcVersion = reader.ReadUInt();
            Program = reader.ReadUInt();
            Version = reader.ReadUInt();
            Procedure = reader.ReadUInt();
            Credential = new OpaqueAuthentication(reader);
            Verifier = new OpaqueAuthentication(reader);
        }
    }

    internal enum MessageType
    {
        Call = 0,
        Reply = 1,
    }

    internal partial class MismatchInfo : IXdrReadable, IXdrWritable
    {
        public uint Low { get; set; }
        public uint High { get; set; }

        public MismatchInfo()
        {
        }

        public MismatchInfo(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write(Low);
            writer.Write(High);
        }

        public void ReadFrom(IXdrReader reader)
        {
            Low = reader.ReadUInt();
            High = reader.ReadUInt();
        }
    }

    internal partial class OpaqueAuthentication : IXdrReadable, IXdrWritable
    {
        public AuthenticationFlavor AuthenticationFlavor { get; set; }
        public byte[] Body { get; set; }

        public OpaqueAuthentication()
        {
        }

        public OpaqueAuthentication(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write((int)AuthenticationFlavor);
            writer.WriteVariableLengthOpaque(Body);
        }

        public void ReadFrom(IXdrReader reader)
        {
            AuthenticationFlavor = (AuthenticationFlavor)reader.ReadInt();
            Body = reader.ReadOpaque();
        }
    }

    internal partial class RejectedReply : IXdrReadable, IXdrWritable
    {
        public RejectStatus RejectStatus { get; set; }
        public MismatchInfo MismatchInfo { get; set; }
        public AuthenticationStatus AuthenticationStatus { get; set; }

        public RejectedReply()
        {
        }

        public RejectedReply(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write((int)RejectStatus);
            switch (RejectStatus)
            {
                case RejectStatus.RpcVersionMismatch:
                    MismatchInfo?.WriteTo(writer);
                    break;
                case RejectStatus.AuthenticationError:
                    writer.Write((int)AuthenticationStatus);
                    break;
            }
        }

        public void ReadFrom(IXdrReader reader)
        {
            RejectStatus = (RejectStatus)reader.ReadInt();
            switch (RejectStatus)
            {
                case RejectStatus.RpcVersionMismatch:
                    MismatchInfo = new MismatchInfo(reader);
                    break;
                case RejectStatus.AuthenticationError:
                    AuthenticationStatus = (AuthenticationStatus)reader.ReadInt();
                    break;
            }
        }
    }

    internal enum RejectStatus
    {
        RpcVersionMismatch = 0,
        AuthenticationError = 1,
    }

    internal partial class ReplyBody : IXdrReadable, IXdrWritable
    {
        public ReplyStatus ReplyStatus { get; set; }
        public AcceptedReply AcceptedReply { get; set; }
        public RejectedReply RejectedReply { get; set; }

        public ReplyBody()
        {
        }

        public ReplyBody(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write((int)ReplyStatus);
            switch (ReplyStatus)
            {
                case ReplyStatus.Accepted:
                    AcceptedReply?.WriteTo(writer);
                    break;
                case ReplyStatus.Denied:
                    RejectedReply?.WriteTo(writer);
                    break;
            }
        }

        public void ReadFrom(IXdrReader reader)
        {
            ReplyStatus = (ReplyStatus)reader.ReadInt();
            switch (ReplyStatus)
            {
                case ReplyStatus.Accepted:
                    AcceptedReply = new AcceptedReply(reader);
                    break;
                case ReplyStatus.Denied:
                    RejectedReply = new RejectedReply(reader);
                    break;
            }
        }
    }

    internal partial class ReplyData : IXdrReadable, IXdrWritable
    {
        public AcceptStatus AcceptStatus { get; set; }
        public MismatchInfo MismatchInfo { get; set; }

        public ReplyData()
        {
        }

        public ReplyData(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write((int)AcceptStatus);
            switch (AcceptStatus)
            {
                case AcceptStatus.Success:
                    break;
                case AcceptStatus.ProgramMismatch:
                    MismatchInfo?.WriteTo(writer);
                    break;
                default:
                    break;
            }
        }

        public void ReadFrom(IXdrReader reader)
        {
            AcceptStatus = (AcceptStatus)reader.ReadInt();
            switch (AcceptStatus)
            {
                case AcceptStatus.Success:
                    break;
                case AcceptStatus.ProgramMismatch:
                    MismatchInfo = new MismatchInfo(reader);
                    break;
                default:
                    break;
            }
        }
    }

    internal enum ReplyStatus
    {
        Accepted = 0,
        Denied = 1,
    }

    internal partial class RpcMessage : IXdrReadable, IXdrWritable
    {
        public uint Xid { get; set; }
        public Body Body { get; set; }

        public RpcMessage()
        {
        }

        public RpcMessage(IXdrReader reader)
        {
            ReadFrom(reader);
        }

        public void WriteTo(IXdrWriter writer)
        {
            writer.Write(Xid);
            Body?.WriteTo(writer);
        }

        public void ReadFrom(IXdrReader reader)
        {
            Xid = reader.ReadUInt();
            Body = new Body(reader);
        }
    }
}
